# Generated by Django 5.2.3 on 2025-07-02 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_name', models.CharField(help_text='Full name of the defendant', max_length=200)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('race', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black/African American'), ('HISPANIC', 'Hispanic/Latino'), ('ASIAN', 'Asian'), ('NATIVE', 'Native American'), ('PACIFIC', 'Pacific Islander'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('case_number', models.CharField(help_text='Unique case identifier', max_length=50, unique=True)),
                ('date_filed', models.DateField(blank=True, help_text='Date case was filed', null=True)),
                ('charges', models.TextField(help_text='Multiple charges separated by semicolons or newlines')),
                ('arrest_citation_date', models.DateField(blank=True, help_text='Date of arrest or citation', null=True)),
                ('parish', models.CharField(help_text='Parish where case was filed', max_length=100)),
                ('alert_available', models.BooleanField(default=False, help_text='Whether alert is available')),
                ('scraped_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was scraped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Criminal Record',
                'verbose_name_plural': 'Criminal Records',
                'db_table': 'criminal_records',
                'ordering': ['-scraped_timestamp'],
                'indexes': [models.Index(fields=['case_number'], name='criminal_re_case_nu_2073c5_idx'), models.Index(fields=['defendant_name'], name='criminal_re_defenda_2b9f53_idx'), models.Index(fields=['parish'], name='criminal_re_parish_561e91_idx'), models.Index(fields=['scraped_timestamp'], name='criminal_re_scraped_becec8_idx')],
            },
        ),
    ]
